### ISSUE TITLE
Familiarizarse con Mongo.db

### ISSUE THREAD

**Issue by UO270762** [Arquisoft/dede_es1c#12]
Leer  documentacion y hacer pruebas sobre su funcionamiento de cara a desarrollar en el proyecto
- [x] Laura
- [x] Hector
- [x] Alvaro
- [x] Ivan

**Comment by UO270762** [comment]
Info de web oficial: https://www.mongodb.com/es/what-is-mongodb

**Comment by uo239198** [comment]
Adjunto información que puede resultar útil: 
Documentación oficial: [https://docs.mongodb.com/](url)
Un vídeo de un canal tecnológico: [https://www.youtube.com/watch?v=lWMemPN9t6Q](url)

**Comment by uo239198** [comment]
Este artículo de IONOS también puede resultar de interés:

[https://www.ionos.es/digitalguide/paginas-web/desarrollo-web/tutorial-de-mongodb-primeros-pasos/](url)

**Comment by uo239198** [comment]
Cerramos esta issue. En la reunión de hoy ya se han comentado lo necesario para abordar el comiendo del backend junto a lo investigado anteriormente.
