### ISSUE TITLE
Doc: Decisiones de diseño

### ISSUE THREAD

**Issue by uo239198** [Arquisoft/dede_es1c#15]

**Comment by uo239198** [comment]
Por el momento creo que respecto a las decisiones de diseño, podemos plantear la utilización de la BD, el lenguaje de programación y las librerías.

**Comment by UO270762** [comment]
> Por el momento creo que respecto a las decisiones de diseño, podemos plantear la utilización de la BD, el lenguaje de programación y las librerías. @UO270762 @seirin16 @uo271432 ¿Qué os parece?

Yo creo que esta bien, dejar reflejado que nos hemos decantado por mongoDB y el motivo

**Comment by seirin16** [comment]
Me parece bien, además de que ya hemos hablado de que utilizar de forma casi segura.

**Comment by uo239198** [comment]
Cierro la ISSUE después de que hayais aceptado el PULL REQUEST, iré actualizando el documento según sigamos tomando más decisiones sobre el diseño de la aplicación.
