### ISSUE TITLE
Cambiar el link de los test al de despliegue

### ISSUE THREAD

**Issue by uo271432** [Arquisoft/dede_es1c#270]
Realizar el cambio de los links de los test de aceptación:
- [x]  Realizar el registro de un usuario sin POD
- [x] Realizar el inicio de sesión de un usuario con POD
- [x] Añadir un producto al carrito
- [x] Filtrar por nombre producto
- [x] Filtrar por categoría producto
- [x] Logearse POD malo
- [x] Mostrar producto individual
- [x] Logout
- [x] Pago con datos de tarjeta validos
- [x] Pago con datos de tarjtea invaldios

**Comment by UO270762** [comment]
- [] Pago con datos de tarjeta validos
- [] Pago con datos de tarjtea invaldios

**Comment by UO270762** [comment]
Actualizado con link de despliegue
