### ISSUE TITLE
Doc: Puntos 3,5,6

### ISSUE THREAD

**Issue by UO270762** [Arquisoft/dede_es1c#31]
Complementar los puntos anteriormente mencionados de la documentacion

**Comment by UO270762** [comment]
Comienzo a desarrollar el punto 3 de la documentacion

**Comment by UO270762** [comment]
> Comienzo a desarrollar el punto 3 de la documentacion

Punto 3 de la documentacion completado

**Comment by uo271432** [comment]
Comienzo el apartado 6 de la documentación

**Comment by uo271432** [comment]
> Comienzo el apartado 6 de la documentación

Acabado el punto 6

**Comment by UO270762** [comment]
Punto 5 terminado
